### ISSUE TITLE
Only matching lowercase file extension

### ISSUE THREAD

**Issue by umeditor** [J-PAL/PII-Scan#15]
We currently only scanning files that end with .dta, . sas7bdat or .csv. Should we ignore case, and also search for .DTA, . SAS7BDAT or .CSV? If so, what about mixed cased (.dtA, .sas7BDAT, .cSv, etc.)?

**Comment by joshjacobson** [comment]
I'd think there's really no reason to be so specific... I'd transform the extension to lowercase, and then do one check.

**Comment by umeditor** [comment]
Let's not deal with this until it's a real issue. We've got enough work on our plates for now.
